[package]
name = "rog"
version = "0.1.9"
edition = "2021"
authors = ["mohanson <mohanson@outlook.com>"]
description = "A Rust logger"
license = "MIT"
homepage = "https://github.com/rsdump/rog"
documentation = "https://github.com/rsdump/rog/blob/master/README.md"

[dependencies]
